Add Rawhide vs ELN in FAQ
fedora-eln/eln-docs pull request #23
Opened 2021-11-09 21:57 UTC by tdawson

Signed-off-by: Troy Dawson <tdawson@redhat.com>

2021-11-10 09:59 UTC, jkonecny12 commented
Looks great to me. Thanks!

2021-11-10 13:58 UTC, bookwar commented
There is a dedicated page which describes the buildroot setup of ELN https://docs.fedoraproject.org/en-US/eln/buildroot/

Maybe we can move the table which describes the buildroot configuration from FAQ there. And link to it from FAQ? So that we have one place for all buildroot information.

2021-11-10 14:05 UTC, sgallagher requested changes

2021-11-10 14:05 UTC, sgallagher commented on modules/ROOT/pages/faq.adoc
> +    to differ.  Listing all of those differences is beyond the scope of this document.
```suggestion
    Note: Many packages have %if fedora / rhel conditionals in their specfiles that produce differences between the built Rawhide and ELN packages.  Listing all of those differences is beyond the scope of this document.
```

2021-11-10 14:05 UTC, sgallagher commented on modules/ROOT/pages/faq.adoc
> +    https://github.com/fedora-eln/eln/issues/new/choose[issue tracker].
```suggestion
    Never.  In nearly all cases, you actually want to use the %\{rhel} macro. If you think you need to use the %\{eln} macro, file a ticket on the https://github.com/fedora-eln/eln/issues/new/choose[issue tracker] with your justification.
```

2021-11-11 19:07 UTC, tdawson commented
I used all of Stephens suggestions.
I have moved the buildroot stuff, over to the buildroot page, with links.
I have updated the buildroot page with the latest compiler flag info.

An example is found here:
https://tdawson.fedorapeople.org/eln/public/eln/faq/
https://tdawson.fedorapeople.org/eln/public/eln/buildroot/

2021-11-11 19:31 UTC, sgallagher requested changes
Additionally (though this could be a separate change if you prefer), there's a section on the buildroot page that could be updated:

Simply specify `eln` as the target when kicking off a `koji` build using `fedpkg`:
```
fedpkg build [--scratch] --target eln [--srpm [SRPM]] [...]
```

Could be simplified to
Simply specify `eln` as the release when kicking off a `koji` build using `fedpkg`:
```
fedpkg --release eln build [--scratch] [--srpm [SRPM]] [...]
```


I mostly note this because the existing example is actually wrong. You would need to specify both `--target eln` and `--skip-nvr-check` for it to work properly, whereas `--release eln` handles it correctly.

2021-11-11 19:31 UTC, sgallagher commented on modules/ROOT/pages/faq.adoc
> +What is the differences between Rawhide and ELN?::
```suggestion
What are the differences between Rawhide and ELN?::
```

2021-11-11 19:58 UTC, sgallagher approved these changes
LGTM

2021-11-11 20:02 UTC, merged