branching: add image version bump
fedora-eln/eln-docs pull request #41
Opened 2024-06-25 20:19 UTC by yselkowitz

This was missed entirely during 10 but is now fixed for 11.

https://pagure.io/pungi-fedora/pull-request/1294

BTW I don't have privileges in this repo.

/cc @sgallager

2024-06-25 20:28 UTC, sgallagher requested changes

2024-06-25 20:28 UTC, sgallagher commented on build.sh
> +        podman --remote run --rm -it -v "$(pwd):/antora:z" "${image}" ${cmd}
This doesn't look related

2024-06-25 21:37 UTC, yselkowitz commented on build.sh
> +        podman --remote run --rm -it -v "$(pwd):/antora:z" "${image}" ${cmd}
Fixed.

2024-06-26 12:40 UTC, sgallagher approved these changes

2024-06-26 12:40 UTC, merged